name: 'Local Cache on Self-Hosted'
description: 'Cache dependencies and build outputs to improve workflow execution time on self hosted machine'

inputs:
  path:
    description: 'File or folder to be cached'
    required: true
  action:
    description: 'Action will be run if cache not found'
    required: true
  cache-key:
    description: 'Explicit key for versioning the cache'
    required: true
  cache-dir:
    description: 'Path dir will cache'
    required: true
  
outputs:
  cache-hit:
    description: 'A boolean value to indicate if cache was found and restored'

branding:
  icon: 'play'
  color: 'green'

runs:
  using: 'composite'
  steps:
    - name: Cache Environment Config
      shell: bash
      run: |
        echo "TARGET_PATH=${{ inputs.path }}" >> $GITHUB_ENV
        echo "TARGET_ACTION=${{ inputs.action }}" >> $GITHUB_ENV
        echo "CACHE_KEY=${{ inputs.cache-key }}" >> $GITHUB_ENV
        echo "CACHE_DIR=${{ inputs.cache-dir }}" >> $GITHUB_ENV

    - name: Cache Variables Check
      shell: bash
      run: source ${{ github.action_path }}/scripts/setup.sh

    - name: Cache Restore
      shell: bash
      id: cache-hit
      run: source ${{ github.action_path }}/scripts/restore.sh

    - name: Cache Action
      shell: bash
      if: steps.cache-hit.outputs.cache-hit != 'true'
      run: source ${{ github.action_path }}/scripts/action.sh

    - name: Cache Save
      shell: bash
      run: source ${{ github.action_path }}/scripts/save.sh
