name: 'Local Cache on Self-Hosted'
description: 'Cache dependencies and build outputs to improve workflow execution time on self hosted machine'

inputs:
  path:
    description: 'File or folder to be cached'
    required: true
  action:
    description: 'Action will be run if cache not found'
    required: true
  cache-key:
    description: 'Explicit key for versioning the cache'
    required: true
  cache-dir:
    description: 'Path dir will cache'
    required: true
  
outputs:
  cache-hit:
    description: 'A boolean value to indicate if cache was found and restored'

branding:
  icon: 'play'
  color: 'green'

runs:
  using: 'composite'
  steps:
    - name: Store Inputs Value
      shell: bash
      id: inputs_file
      run: |
        FILE_PATH=$(pwd)/inputs.txt
        echo "${{ inputs.path }}" > $FILE_PATH
        echo "${{ inputs.action }}" >> $FILE_PATH
        echo "${{ inputs.cache-key }}" >> $FILE_PATH
        echo "${{ inputs.cache-dir }}" >> $FILE_PATH
        echo "${{ inputs.cache-dir }}/${{ inputs.cache-key }}" >> $FILE_PATH
        echo "INPUT_FILE_PATH=$(pwd)/inputs.txt" >> $GITHUB_ENV
        echo "path=$FILE_PATH" >> "$GITHUB_OUTPUT"

    - name: Check Inputs Value
      shell: bash
      run: source ${{ github.action_path }}/scripts/check_inputs.sh ${{ steps.inputs_file.outputs.path }}

    - name: Cache Restore
      shell: bash
      id: check_cache
      run: source ${{ github.action_path }}/entrypoint.sh ${{ steps.inputs_file.outputs.path }}

    - name: Clean Inputs File
      shell: bash
      run: rm -rf ${{ steps.inputs_file.outputs.path }}
