name: 'Local Cache on Self-Hosted'
description: 'Cache dependencies and build outputs to improve workflow execution time on self hosted machine'

inputs:
  path:
    description: 'File or folder to be cached'
    required: true
  action:
    description: 'Action will be run if cache not found'
    required: true
  cache-key:
    description: 'Explicit key for versioning the cache'
    required: true
  cache-dir:
    description: 'Path dir will cache'
    required: true
  
outputs:
  cache-hit:
    description: 'A boolean value to indicate if cache was found and restored'

branding:
  icon: 'play'
  color: 'green'

runs:
  using: 'composite'
  s: 'docker'
  env:
    TARGET_PATH: ${{ inputs.path }}
    TARGET_ACTION: ${{ inputs.action }}
    CACHE_KEY: ${{ inputs.cache-key }}
    CACHE_DIR: ${{ inputs.cache-dir }}
    CACHE_PATH: ${{ inputs.cache-dir }}/${{ inputs.cache-key }}
  steps:
    - name: Store Inputs Value
      shell: bash
      id: inputs_file
      run: |
        echo "TARGET_PATH=${{ inputs.path }}" >> $GITHUB_ENV
        echo "TARGET_ACTION=${{ inputs.action }}" >> $GITHUB_ENV
        echo "CACHE_KEY=${{ inputs.cache-key }}" >> $GITHUB_ENV
        echo "CACHE_DIR=${{ inputs.cache-dir }}" >> $GITHUB_ENV
        echo "CACHE_PATH=${{ inputs.cache-dir }}/${{ inputs.cache-key }}" >> $GITHUB_ENV

    - name: Check Inputs Value
      shell: bash
      run: source ${{ github.action_path }}/scripts/setup.sh

    - name: Cache Restore
      shell: bash
      id: check_cache
      run: source ${{ github.action_path }}/scripts/restore.sh

    - name: Clean Workflow
      shell: bash
      run: source ${{ github.action_path }}/scripts/clean.sh
