name: 'Local Cache'
description: "Github Action to save and restore files across job runs on self-hosted runner"

inputs:
  TARGET_PATH:
    description: 'File or folder to be cached'
    required: true
  TARGET_ACTION:
    description: 'Action will be run if cache not found'
    required: true
  CACHE_KEY:
    description: 'Explicit key for versioning the cache'
    required: true
  CACHE_PATH:
    description: 'Path dir will cache'
    required: true
  
outputs:
  cache-hit:
    description: 'A boolean value to indicate if cache was found and restored'

branding:
  icon: 'play'
  color: 'green'

runs:
  using: 'composite'
  steps:
    - name: Create Inputs File
      shell: bash
      id: inputs_file
      run: |
        FILE_PATH=${{ github.action_path }}/inputs.txt
        echo "${{ inputs.TARGET_PATH }}" > $FILE_PATH
        echo "${{ inputs.TARGET_ACTION }}" >> $FILE_PATH
        echo "${{ inputs.CACHE_KEY }}" >> $FILE_PATH
        echo "${{ inputs.CACHE_PATH }}" >> $FILE_PATH
        echo "${{ inputs.CACHE_PATH }}/${{ inputs.CACHE_KEY }}" >> $FILE_PATH
        echo "path=$FILE_PATH" >> "$GITHUB_OUTPUT"

    - name: Cache Restore
      shell: bash
      id: check_cache
      run: source ${{ github.action_path }}/entrypoint.sh ${{ steps.inputs_file.outputs.path }}

    - name: Clean Inputs File
      shell: bash
      run: rm -rf ${{ steps.inputs_file.outputs.path }}
