name: 'Local Cache on Self-Hosted'
description: 'Cache dependencies and build outputs to improve workflow execution time on self hosted machine'

inputs:
  path:
    description: 'File or folder to be cached'
    required: true
  action:
    description: 'Action will be run if cache not found'
    required: true
  cache-key:
    description: 'Explicit key for versioning the cache'
    required: true
  cache-dir:
    description: 'Path dir will cache'
    required: true
  
outputs:
  cache-hit:
    description: 'A boolean value to indicate if cache was found and restored'

branding:
  icon: 'play'
  color: 'green'

runs:
  using: 'composite'
  steps:
    - name: Cache Variables Config
      shell: bash
      run: |
        FILE_PATH=$(pwd)/inputs.txt
        echo "${{ inputs.TARGET_PATH }}" > $FILE_PATH
        echo "${{ inputs.TARGET_ACTION }}" >> $FILE_PATH
        echo "${{ inputs.CACHE_KEY }}" >> $FILE_PATH
        echo "${{ inputs.CACHE_PATH }}" >> $FILE_PATH
        echo "${{ inputs.CACHE_PATH }}/${{ inputs.CACHE_KEY }}" >> $FILE_PATH

    - name: Cache Variables Check
      shell: bash
      run: source ${{ github.action_path }}/scripts/setup.sh

    - name: Cache Restore
      shell: bash
      id: cache-hit
      run: source ${{ github.action_path }}/scripts/restore.sh

    - name: Cache Action
      shell: bash
      if: steps.cache-hit.outputs.cache-hit != 'true'
      run: source ${{ github.action_path }}/scripts/action.sh

    - name: Cache Save
      shell: bash
      run: source ${{ github.action_path }}/scripts/save.sh

    - name: Clean Action
      shell: bash
      run: source ${{ github.action_path }}/scripts/clean.sh
